version: '3'
services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'meldcx_mysql:/var/lib/mysql'
        networks:
            - meldcx_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8080:80
        networks:
            - meldcx_network
        environment: 
          PMA_HOST: mysql
          PMA_USER: root
          PMA_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            - mysql

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - meldcx_network
networks:
    meldcx_network:
        driver: bridge
volumes:
    meldcx_mysql:
        driver: local
